// SPDX-License-Identifier: BSD-3-Clause
// Auto-generated by train_wov_tflm.py — do not edit.

#ifndef G_HEY_LINUX_QUANTIZED_MODEL_DATA_H_
#define G_HEY_LINUX_QUANTIZED_MODEL_DATA_H_

#include <cstddef>
#include <cstdint>

extern const unsigned char g_hey_linux_quantized_model_data[];
extern const size_t g_hey_linux_quantized_model_data_size;

#endif  // G_HEY_LINUX_QUANTIZED_MODEL_DATA_H_
