// SPDX-License-Identifier: BSD-3-Clause
// Auto-generated by sof_tflm_train.py — do not edit.

#ifndef SOF_TFLM_LABELS_H_
#define SOF_TFLM_LABELS_H_

#define TFLM_CATEGORY_COUNT  3
#define TFLM_CATEGORY_DATA   { "silence", "unknown", "hey_linux", }

#endif  // SOF_TFLM_LABELS_H_
