# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2026 Intel Corporation. All rights reserved.
"""
Train a tflite-micro ``tiny_conv`` DS-CNN wake-word model against SOF mel40
features and emit a drop-in replacement for
``src/audio/tensorflow/micro_speech_quantized_model_data.{cc,h}``.

Architecture matches ``MicroMutableOpResolver<4>`` in
``src/audio/tensorflow/speech.cc``:

    Reshape -> DepthwiseConv2D -> FullyConnected -> Softmax

Consumes features produced by ``run_mfcc_train.sh`` via ``mel40_dataset.py``.
Writes ``<out_dir>/<name>_quantized_model.tflite``, a ``xxd``-style C array
under the same basename, and a matching header. The C array symbol defaults
to ``g_<name>_quantized_model_data``.

Constraints preserved for the tflmcly KPB rule:
    label index 0 = silence
    label index 1 = unknown
    label index >= 2 = keyword(s) that trigger KPB_EVENT_BEGIN_DRAINING

Requires TensorFlow >= 2.10 in an isolated venv (see the module README).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np

import mel40_dataset

try:
    import tensorflow as tf
except ImportError as exc:  # pragma: no cover - only hit outside the venv
    print(
        "tensorflow not importable; activate the tflm-train venv first",
        file=sys.stderr,
    )
    raise SystemExit(1) from exc


def build_tiny_conv(num_classes: int) -> tf.keras.Model:
    """Match tflite-micro's ``create_tiny_conv_model`` topology."""
    inputs = tf.keras.Input(
        shape=(mel40_dataset.WINDOW_HOPS, mel40_dataset.HOP_BINS, 1),
        name="mel40",
    )
    x = tf.keras.layers.DepthwiseConv2D(
        depth_multiplier=8,
        kernel_size=(10, 8),
        strides=(2, 2),
        padding="same",
        activation="relu",
        name="dwconv",
    )(inputs)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Flatten()(x)
    logits = tf.keras.layers.Dense(num_classes, name="logits")(x)
    outputs = tf.keras.layers.Softmax(name="prob")(logits)
    return tf.keras.Model(inputs=inputs, outputs=outputs, name="tiny_conv")


def split_train_val(
    X: np.ndarray,
    y: np.ndarray,
    val_frac: float,
    seed: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Stratified split with a fixed RNG so runs are reproducible."""
    rng = np.random.default_rng(seed)
    idx = np.arange(y.size)
    train_mask = np.zeros(y.size, dtype=bool)
    for c in np.unique(y):
        cls_idx = idx[y == c]
        rng.shuffle(cls_idx)
        cut = int(round(cls_idx.size * (1.0 - val_frac)))
        train_mask[cls_idx[:cut]] = True
    return X[train_mask], y[train_mask], X[~train_mask], y[~train_mask]


def representative_dataset(
    X: np.ndarray,
    y: np.ndarray,
    n_samples: int,
):
    """Yield calibration inputs stratified across classes.

    Uniform random picks under-represent minority classes (e.g. a positive
    keyword class with ~5% of the data), which biases int8 activation
    scales toward the majority class and destroys keyword recall after
    quantization. Pick roughly ``n_samples / n_classes`` per class.
    """
    rng = np.random.default_rng(0)
    classes = np.unique(y)
    per_class = max(1, n_samples // classes.size)
    picks: list[int] = []
    for c in classes:
        cls_idx = np.where(y == c)[0]
        take = min(per_class, cls_idx.size)
        picks.extend(rng.choice(cls_idx, size=take, replace=False).tolist())
    rng.shuffle(picks)
    for i in picks:
        yield [X[i : i + 1].astype(np.float32)]


def convert_to_tflite_int8(
    model: tf.keras.Model,
    rep_X: np.ndarray,
    rep_y: np.ndarray,
    n_rep: int,
) -> bytes:
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_dataset(
        rep_X, rep_y, n_rep
    )
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS_INT8
    ]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def emit_c_array(
    tflite_bytes: bytes,
    out_cc: Path,
    out_h: Path,
    symbol: str,
) -> None:
    """Emit the same layout as micro_speech_quantized_model_data.{cc,h}."""
    guard = symbol.upper() + "_H_"
    with open(out_h, "w") as f:
        f.write(f"// SPDX-License-Identifier: BSD-3-Clause\n")
        f.write(f"// Auto-generated by train_wov_tflm.py — do not edit.\n\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <cstddef>\n#include <cstdint>\n\n")
        f.write(f"extern const unsigned char {symbol}[];\n")
        f.write(f"extern const size_t {symbol}_size;\n\n")
        f.write(f"#endif  // {guard}\n")

    with open(out_cc, "w") as f:
        f.write("// SPDX-License-Identifier: BSD-3-Clause\n")
        f.write("// Auto-generated by train_wov_tflm.py — do not edit.\n\n")
        f.write(f'#include "{out_h.name}"\n\n')
        # Force 8-byte alignment to match tflite-micro flatbuffer expectations.
        f.write(
            f"alignas(8) const unsigned char {symbol}[] = {{\n"
        )
        line = "    "
        for i, b in enumerate(tflite_bytes):
            line += f"0x{b:02x}, "
            if (i + 1) % 12 == 0:
                f.write(line.rstrip() + "\n")
                line = "    "
        if line.strip():
            f.write(line.rstrip() + "\n")
        f.write("};\n\n")
        f.write(f"const size_t {symbol}_size = {len(tflite_bytes)};\n")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--feat-root", required=True)
    ap.add_argument(
        "--labels",
        nargs="+",
        required=True,
        help="Class labels in index order; put silence first, unknown second.",
    )
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--name", default="hey_linux",
                    help="Base name for output files and C symbol.")
    ap.add_argument("--epochs", type=int, default=25)
    ap.add_argument("--batch-size", type=int, default=128)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--val-frac", type=float, default=0.15)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--rep-samples", type=int, default=1500,
                    help="Total calibration samples for int8 (stratified per class).")
    ap.add_argument("--window-hop-step", type=int, default=None,
                    help="Windowing stride in hops (default: non-overlapping).")
    ap.add_argument("--feature-clip-min", type=float, default=-1.0,
                    help="Lower bound applied to features before training/calibration.")
    ap.add_argument("--feature-clip-max", type=float, default=4.0,
                    help="Upper bound applied to features. Rare mel-log outliers above "
                         "this get clipped; the int8 saturation on-device produces the "
                         "same behaviour at inference.")
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    tf.keras.utils.set_random_seed(args.seed)

    print(f">>> Loading features from {args.feat_root}")
    X, y = mel40_dataset.load_dataset(
        args.feat_root, args.labels, hop_step=args.window_hop_step
    )
    print(f"    X={X.shape} y={y.shape} counts={np.bincount(y).tolist()}")
    if args.feature_clip_min is not None or args.feature_clip_max is not None:
        pre_min, pre_max = float(X.min()), float(X.max())
        X = np.clip(X, args.feature_clip_min, args.feature_clip_max)
        print(f"    clip [{args.feature_clip_min}, {args.feature_clip_max}]: "
              f"range {pre_min:.3f}..{pre_max:.3f} -> {float(X.min()):.3f}..{float(X.max()):.3f}")

        # Linear rescale [clip_min, clip_max] -> [-1, +1] so TFLite
        # calibration picks input_scale=1/128, input_zero_point=0 and the
        # full int8 range is used. Runtime tflm-classify.c mirrors this
        # transform on the Q9.23 mel value before requantization.
        center = 0.5 * (args.feature_clip_min + args.feature_clip_max)
        half_span = 0.5 * (args.feature_clip_max - args.feature_clip_min)
        X = (X - center) / half_span
        print(f"    rescale to [-1, +1] (center={center:.3f}, half_span={half_span:.3f}): "
              f"range {float(X.min()):.3f}..{float(X.max()):.3f}")

    X_tr, y_tr, X_va, y_va = split_train_val(X, y, args.val_frac, args.seed)
    print(f"    train={X_tr.shape[0]} val={X_va.shape[0]}")

    n_classes = len(args.labels)
    model = build_tiny_conv(n_classes)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(args.lr),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(),
        metrics=["accuracy"],
    )
    model.summary(print_fn=lambda s: print("    " + s))

    model.fit(
        X_tr, y_tr,
        validation_data=(X_va, y_va),
        batch_size=args.batch_size,
        epochs=args.epochs,
        verbose=2,
    )

    print(">>> Converting to int8 tflite")
    tflite_bytes = convert_to_tflite_int8(model, X_tr, y_tr, args.rep_samples)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    tflite_path = out_dir / f"{args.name}_quantized_model.tflite"
    tflite_path.write_bytes(tflite_bytes)
    print(f"    wrote {tflite_path} ({len(tflite_bytes)} bytes)")

    symbol = f"g_{args.name}_quantized_model_data"
    out_cc = out_dir / f"{args.name}_quantized_model_data.cc"
    out_h = out_dir / f"{args.name}_quantized_model_data.h"
    emit_c_array(tflite_bytes, out_cc, out_h, symbol)
    print(f"    wrote {out_cc}")
    print(f"    wrote {out_h}")

    labels_path = out_dir / f"{args.name}_labels.txt"
    labels_path.write_text("\n".join(args.labels) + "\n")
    print(f"    wrote {labels_path} (drop into speech.h TFLM_CATEGORY_DATA)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
